version: "3.9"

services:
  db:
    image: postgres:13.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: bookmarkapp
      POSTGRES_PASSWORD: bookmarkapp-pw
      POSTGRES_DB: bookmarkapp
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-bookmarkapp:/var/lib/postgresql/data
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["pnpm", "dev"]
    container_name: bookmarkapp
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - ./bookmarkapp:/app
      - /app/node_modules  # Exclude local node_modules

volumes:
  postgres-bookmarkapp:
